import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Lexend } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import Footer from "../../footer";
import { ColourModeProvider } from "./lib/colourModeContext";
import { WindowSizeProvider } from "./lib/windowSizeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const viewports: Viewport = {
  initialScale: 1,
  width: "device-width",
  minimumScale: 1,
  maximumScale: 1,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ColourModeProvider>
      <WindowSizeProvider>
        <html lang="en">
          <body
            className={`${lexend.className}  antialiased`}
          >
            <Navbar />
            <main className="">
              {children}
            </main >
            <Footer />
          </body>
        </html>
      </WindowSizeProvider>
    </ColourModeProvider>

  );
}
